### ISSUE TITLE
"Save As" doesn't copy uploaded files 

### ISSUE THREAD

**Issue by mdpiper** [csdms/wmt-client#69]
To reproduce:

1. Open the public model "Sedflux3D Default". It uses a user-defined sea level file **my_sea_level.csv**.
1. Use the *More > Save model as...* menu item to save the model locally.
1. Run the local copy of the model.

**Expected result**: model runs.
**Actual result**: model fails because it's missing the sea-level file. Here's the stack trace:

Traceback (most recent call last): File "/data/web/htdocs/wmt/api/dev/internal/wmt/controllers/run.py", line 103, in POST submissions.stage(form.d.uuid) File "/data/web/htdocs/wmt/api/dev/internal/wmt/models/submissions.py", line 150, in stage stage_component(path, component) File "/data/web/htdocs/wmt/api/dev/internal/wmt/models/submissions.py", line 212, in stage_component hooks['post-stage'].execute(component['parameters']) File "/data/web/htdocs/wmt/api/dev/db/components/sedflux3d/hooks/post-stage.py", line 11, in execute src = find_simulation_input_file(env['sea_level_file']) File "/data/web/htdocs/wmt/api/dev/internal/wmt/utils/hook.py", line 38, in find_simulation_input_file return find_file_in_search_path(filename, 'WMT_INPUT_FILE_PATH') File "/data/web/htdocs/wmt/api/dev/internal/wmt/utils/hook.py", line 34, in find_file_in_search_path raise FileNotFoundError(filename, paths) FileNotFoundError: my_sea_level.csv: file not found search paths: /data/web/htdocs/wmt/api/dev/db/components/sedflux3d/files /data/web/htdocs/wmt/api/dev/files/uploads/826 / 

We should check whether a model has uploaded files and transfer them to the copy of the model.

**Comment by mdpiper** [comment]
A workaround:

1. Run the original model.
2. Download the results.
3. Get the custom file(s) from the results.
4. Use *Save model as...* to make a copy of the original model.
5. Upload the custom file(s) to the copied model.

**Comment by mdpiper** [comment]
Cases:
* *Save as* from a private model the user owns 👍 
* *Save as* from a public model the user owns 👍 
* *Save* from a public model the user doesn't own 👎 
* *Save as* from a a public model the user doesn't own 👎
